services:

  nginx:
    image: nginx:alpine
    container_name: inventory_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - shared_network

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: inventory_app
    restart: unless-stopped
    working_dir: /var/www/html
    user: "${DOCKER_UID}:${DOCKER_UID}"
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - shared_network

  node:
    image: node:20-alpine
    container_name: inventory_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5175:5175"
    command: sh -c "npm install && npm run dev"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
